### ISSUE TITLE
TODO for release

### ISSUE THREAD

**Issue by gw2princeps** [discretize/gw2-ui#20]
Bunch of things that should be done: 
- [ ] proper translation support for all strings
- [ ] add a way to prefill the cache / some way to deal with SSR
- [ ] improved error handling: API is down right now, but the error displayed says "Network Error"
